export const photos = [
  { src: '/gallery/Gallery_1.webp', title: 'Ranní rozcvička' },
  { src: '/gallery/Gallery_2.webp', title: 'Startovní čára' },
  { src: '/gallery/Gallery_3.webp', title: 'Běh v horách' },
  { src: '/gallery/Gallery_4.webp', title: 'Správná technika' },
  { src: '/gallery/Gallery_5.webp', title: 'Večerní tempo' },
  { src: '/gallery/Gallery_6.webp', title: 'Městský běh' },
  { src: '/gallery/Gallery_7.webp', title: 'Závodní nasazení' },
  { src: '/gallery/Gallery_8.webp', title: 'Zasloužený odpočinek' },
  { src: '/gallery/Gallery_9.webp', title: 'Soustředění' },
  { src: '/gallery/Gallery_10.webp', title: 'Příprava na start' },
  { src: '/gallery/Gallery_11.webp', title: 'Radost z pohybu' },
  { src: '/gallery/Gallery_12.webp', title: 'Běžecká komunita' },
  { src: '/gallery/Gallery_13.webp', title: 'Překonávání limitů' },
  { src: '/gallery/Gallery_14.webp', title: 'Nové obzory' },
  { src: '/gallery/Gallery_15.webp', title: 'Síla a vytrvalost' },
  { src: '/gallery/Gallery_16.webp', title: 'Cesta k cíli' },
  { src: '/gallery/Gallery_17.webp', title: 'Rychlostní trénink' },
  { src: '/gallery/Gallery_18.webp', title: 'Relaxace po běhu' },
];
